- name: Deploy to Heroku
  uses: AkhileshNS/heroku-deploy@v3.0.0
  with:
    # This will be used for authentication. You can find it in your heroku homepage account settings
    heroku_api_key: 4597a2b8-8c6a-49de-9690-9a060765ffe5
    # Email that you use with heroku
    heroku_email: julesmoundi@gmail.com
    # The appname to use for deploying/updating
    heroku_app_name: jules-weather-application
    # An optional buildpack to use when creating the heroku application
    buildpack: # optional
    # The branch that you would like to deploy to Heroku
    branch: # optional, default is HEAD
    # Set this to true if you don't want to use --force when switching branches
    dontuseforce: # optional
    # Will deploy using Dockerfile in project root.
    usedocker: # optional
